// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Book is the predicate function for book builders.
type Book func(*sql.Selector)

// Lock is the predicate function for lock builders.
type Lock func(*sql.Selector)

// Miss is the predicate function for miss builders.
type Miss func(*sql.Selector)

// Token is the predicate function for token builders.
type Token func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
