import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import React from "react";
import { Container, Paper, Grid, Button, Typography } from "@mui/material";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  //ルーター
  const router = useRouter();

  //サインアップクリック
  const SignUpClick = () => {
    router.push("/SignUp");
  };

  //サインインクリック
  const SignInClick = () => {
    router.push("/SignIn");
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          <Typography variant="h1" align="center" gutterBottom>
            BookManager
          </Typography>
          <Container maxWidth="md" sx={{ padding: 4 }}>
            <Paper sx={{ padding: 8, marginTop: 4, boxShadow: 8 }}>
              <Grid container spacing={4} justifyContent="center">
                <Grid item xs={12} textAlign="center">
                  <Typography
                    variant="body1"
                    gutterBottom
                    style={{
                      fontFamily: "Arial, sans-serif",
                      fontSize: "1.25rem",
                    }}
                  >
                    サインインまたはサインアップを選択してください。
                  </Typography>
                </Grid>
                <Grid item xs={6} textAlign="center">
                  <Button
                    variant="outlined"
                    color="primary"
                    onClick={SignInClick}
                    fullWidth
                  >
                    <Typography
                      variant="h3"
                      gutterBottom
                      style={{
                        fontFamily: "Roboto, sans-serif",
                        fontSize: "2rem",
                      }}
                    >
                      サインイン
                    </Typography>
                  </Button>
                </Grid>
                <Grid item xs={6} textAlign="center">
                  <Button
                    variant="outlined"
                    color="primary"
                    onClick={SignUpClick}
                    fullWidth
                  >
                    <Typography
                      variant="h3"
                      gutterBottom
                      style={{
                        fontFamily: "Roboto, sans-serif",
                        fontSize: "2rem",
                      }}
                    >
                      サインアップ
                    </Typography>
                  </Button>
                </Grid>
              </Grid>
            </Paper>
          </Container>
        </div>
      </main>
    </>
  );
}
